# Generated by Django 5.0.6 on 2024-06-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('stock', models.IntegerField()),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='PELUDOS_SHOP_APP/media/platos/', verbose_name='Imagen del producto')),
            ],
            options={
                'verbose_name': 'Plato Proveedor',
                'verbose_name_plural': 'Platos Proveedores',
                'ordering': ['proveedor', 'nombre_producto'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre proveedor')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de contrato')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Repartidores',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Repartidor')),
                ('fecha_contrato', models.DateField(verbose_name='Fecha de contrato')),
                ('telefono', models.CharField(max_length=30, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo')),
                ('disponibilidad', models.BooleanField(default=True, verbose_name='Disponibilidad')),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PELUDOS_SHOP_APP.carrito')),
                ('plato', models.ManyToManyField(to='PELUDOS_SHOP_APP.productoproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='productoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PELUDOS_SHOP_APP.proveedor'),
        ),
        migrations.CreateModel(
            name='RegistroEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En camino', 'En camino'), ('Entregado', 'Entregado')], default='Pendiente', max_length=20)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PELUDOS_SHOP_APP.carrito')),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PELUDOS_SHOP_APP.detallecarrito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PELUDOS_SHOP_APP.repartidores')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.IntegerField(unique=True, verbose_name='run')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_despacho', models.CharField(max_length=50)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_compra', models.DateTimeField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PELUDOS_SHOP_APP.productoproveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PELUDOS_SHOP_APP.userprofile')),
            ],
        ),
    ]
