# Generated by Django 5.0.6 on 2024-06-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PELUDOS_SHOP_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoproveedor',
            options={'ordering': ['proveedor', 'nombre_producto'], 'verbose_name': 'Producto Proveedor', 'verbose_name_plural': 'Productos Proveedores'},
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='metodo_pago',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='PELUDOS_SHOP_APP/media/Producto/', verbose_name='Imagen del producto'),
        ),
    ]
