# Generated by Django 5.0.6 on 2024-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PELUDOS_SHOP_APP', '0002_alter_productoproveedor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoproveedor',
            name='categoria',
            field=models.CharField(choices=[('comida_perros', 'Comida de perros'), ('comida_gatos', 'Comida de gatos'), ('accesorios', 'Accesorios')], default='comida_perros', max_length=20, verbose_name='Categoría'),
        ),
    ]
